services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /home/mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /home/qdrant-data:/qdrant/storage
    restart: always

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:5000"
    volumes:
      - /home/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/syllabuzz
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - mongo
      - qdrant

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - /home/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/syllabuzz
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - mongo
      - qdrant

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      VITE_NODE_ENV: production
      VITE_SERVER_URL: https://server.syllabuzz.buzz
      VITE_BACKEND_URL: https://backend.syllabuzz.buzz
      VITE_SERVER_BASE_URL: https://server.syllabuzz.buzz
    depends_on:
      - server

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/proxy-manager/data:/data
      - /home/proxy-manager/letsencrypt:/etc/letsencrypt

volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      device: /home/uploads

  mongo-data:
    driver: local
    
  qdrant-data:
    driver: local